<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WCSlack\\' => array($baseDir . '/src'),
    'Kerkness\\KoreWP\\' => array($vendorDir . '/kerkness/kore-wp/src'),
);
